default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  database: agenda_mail_development
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

test:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  database: agenda_mail_test
production:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  database: agenda_mail_production
  username: agenda_mail
  password: <%= ENV['DATABASE_PASSWORD'] %>
